# Generated by Django 4.2.2 on 2023-08-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(default=0, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Yvariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Y', models.IntegerField(default=0, verbose_name='Value')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runtest.xvariable')),
            ],
        ),
    ]
